### ISSUE TITLE
Suppot using commands outside of vault

### ISSUE THREAD

**Issue by CamdenClark** [epwalsh/obsidian.nvim#14]
### 🚀 The feature, motivation and pitch

I really want to be able to quickly go to my daily note from another buffer in an entirely different project. it would be awesome to be able to do that outside of the context of the vault that's running!

**Comment by epwalsh** [comment]
Hey @CamdenClark, how we add a setup field like `lazy_setup` that defaults to `true` (to keep backwards compatibility). But in your case you could set this to `false` and have all of the commands available from any buffer.

Want to make a PR?

You'd just have to edit the [`setup`](https://github.com/epwalsh/obsidian.nvim/blob/e3d10fe6bf19f99e7ce289a13f0fc720c2cb276f/lua/obsidian/init.lua#L34) function, and then call the `lazy_setup()` function immediately if `opts.lazy_setup` is `false`, otherwise [`add the autocmd`](https://github.com/epwalsh/obsidian.nvim/blob/e3d10fe6bf19f99e7ce289a13f0fc720c2cb276f/lua/obsidian/init.lua#L73-L78).

**Comment by epwalsh** [comment]
Actually as of #17 commands will always be available ✌️
