### ISSUE TITLE
Add support for note renaming

### ISSUE THREAD

**Issue by Granddave** [epwalsh/obsidian.nvim#207]
### 🚀 The feature, motivation and pitch

In Obsidian, when renaming a note all links to the newly renamed note are automatically updated to point to the name, and thus limit the number of broken links in the vault. This is one of the main features I'm missing while using obsidian.nvim.

I guess what I'm after is to have a command like `:ObsidianRename` that prompts the user for a new note name, searches for backlinks and modifies the backlinks in-place.

### Additional context

This is semi relevant to #189.

**Comment by epwalsh** [comment]
Hey @Granddave I actually started working on this a while ago in https://github.com/epwalsh/obsidian.nvim/pull/91. Unfortunately it fell off my radar but hopefully I'll find the time to get back to it someday 🫤 If someone else were to pick it up I'd be happy to help.

**Comment by epwalsh** [comment]
Well I finally get back to this and I'm pretty happy with it so far. It makes me a little nervous running it though since there's probably some edge cases I've missed, so to mitigate potentially issues from running this command there's two things you can do:
1. Do a dry-run first, e.g. `:ObsidianRename new-note-id --dry-run`, or
2. Commit changes to your vault prior to running it, provided you're using version control.
