### ISSUE TITLE
Add a short intro Video/GIF showing how the plugin can be utilised properly. 

### ISSUE THREAD

**Issue by DMunkei** [epwalsh/obsidian.nvim#41]
### 🚀 The feature, motivation and pitch

Just a small intro video where different scenarios are showcased would be helpful.

**Comment by epwalsh** [comment]
That would definitely be good to have.

**Comment by DMunkei** [comment]
Yea I looked at it and I didn't know how to use it properly haha.

**Comment by epwalsh** [comment]
Totally understandable. It started off as something I was just building for myself and then (to my surprise) a lot of other people started using it, so it's grown a lot since then and now has a lot of features that aren't completely transparent. Can I ask what your main point of confusion was? Was it how to use the commands or autocompletion or just getting it set up properly?

**Comment by DMunkei** [comment]
Getting it set up in general. I got it working, but didn't understand how to use it.

**Comment by aniketgm** [comment]
Anyone on it ? I came across this plugin and wanted to try it out by referring some video/gif. Instead found an issue, LOL.
(I just started using Obsidian UI App) @epwalsh, Videos can be created later, Or I can help make some too, once I become aware of how to use it. Meanwhile can we have like a simple gif in the README. It can help folks get an overview and to get started. What do you think ?

**Comment by DMunkei** [comment]
Haven't done any videos myself, also found myself not using it because I couldn't wrap my head around it. So I'm just waiting for a video/gif. Sounds like a nice idea to have something like that to pull people in.

**Comment by epwalsh** [comment]
This is in the README now.
