### ISSUE TITLE
Blocking output when runing `ObsidianOpen` on Linux

### ISSUE THREAD

**Issue by piero-vic** [epwalsh/obsidian.nvim#47]
### 🐛 Describe the bug

I get output on the neovim command line when running `ObsidianOpen`. The output blocks the command line until Obsidian is closed.

Here's a small video of how it looks.

https://user-images.githubusercontent.com/71156605/200458757-66191443-0c9f-4b09-b305-7aff5f62cb10.mp4

### Versions

`nvim --version`
NVIM v0.8.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

`nvim --headless -c 'lua print(require("obsidian").VERSION)' -c q`
1.6.1

**Comment by epwalsh** [comment]
Hey @piero-vic, I can't view or download the video. But when you say "blocks the command line until Obsidian is closed", are you saying it blocks until the Obsidian desktop app is closed? Or just until you hit ENTER on the command line output?

**Comment by piero-vic** [comment]
Hi @epwalsh, Maybe you can view it [here](https://drive.google.com/file/d/1skd32ogTY1zDwoPtpRrLmJRWWcSZugJB/view). It completely blocks the vim command line so I'm unable to enter any other command. I have to close the Obsidian desktop app to make the output go away.

**Comment by epwalsh** [comment]
Thanks, that worked. Umm that's interesting. That error message you're seeing is probably worth investigating. Internally obsidian.nvim is just shelling out to `xdg-open`: https://github.com/epwalsh/obsidian.nvim/blob/c7e441320280e2b0e51da1efcc241805ef715c34/lua/obsidian/command.lua#L102.

What happens if you call `xdg-open obsidian://open?vault=your-vault-name&file=your-file-name` directly? Same error?

A work-around here would be to just shell out to xdg-open in the background and ignore the result, but then you wouldn't get any feedback in nvim when it fails, which I don't think is ideal.

**Comment by gerryhernandez** [comment]
Following up here, I'm getting a similar issue as the OP. I'm not getting the same errors, but I can 100% reproduce the blocking issue. I'd also like to clarify what's going on.

`xdg-open 'obsidian://open?vault=my_vault&file=test_note.md'` blocks even in the terminal shell. So this is reproducible outside of Neovim. I don't have access to a Mac right now, but I believe `xdg-open` on Linux blocks by default, whereas `open -a` on macOS does not.

I think we need to change the invocation from using `os.execute()`, which is intentionally blocking, to something like a [Plenary Job](https://github.com/nvim-lua/plenary.nvim#plenaryjob). This would allow for an asynchronous handler for when the process exits, so we can still echo a warning if it fails. The flip side to this is that now Plenary becomes a required dependency for your plugin, rather than an optional one.

If you don't mind having Plenary as a required dependency, I can whip up a PR for you. Just say the word!

**Comment by gerryhernandez** [comment]
So the README says that Plenary is an optional dependency, but it's actually bundled as a submodule, so I went ahead and coded a fix/PR. I'm not sure what to do with the README, but here's a working `:ObsidianOpen` on Linux.

As I said in the PR and my previous comment, I could use some help with testing this on macOS. Thanks!

**Comment by epwalsh** [comment]
Thanks @gerryhernandez, I just updated the README: 9728af6
