### ISSUE TITLE
Link Suggestion Completion "bad argument to 'insert'" Error

### ISSUE THREAD

**Issue by BeCracked** [epwalsh/obsidian.nvim#59]
### 🐛 Describe the bug

Steps to reproduce:
1. Open some note in the Obsidian vault
2. Type `[[` followed by any two letters. Note: Numbers do __not__ trigger this bug
3. As soon as the second letter is typed the following error pops up.
```
Error detected while processing TextChangedI Autocommands for "*":
Error executing lua callback: ...te/pack/packer/start/obsidian.nvim/lua/obsidian/note.lua:232: bad argument #1 to 'insert' (table expected, got string)
stack traceback:
        [C]: in function 'insert'
        ...te/pack/packer/start/obsidian.nvim/lua/obsidian/note.lua:232: in function 'from_lines'
        ...te/pack/packer/start/obsidian.nvim/lua/obsidian/note.lua:110: in function '(for generator)'
        ...ite/pack/packer/start/obsidian.nvim/lua/cmp_obsidian.lua:23: in function 'complete'
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:325: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:289: in function 'complete'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:169: in function 'callback'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:219: in function 'autoindent'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:161: in function 'on_change'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:312: in function 'callback'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:23: in function <...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:22>
```
I did not try this in a minimal environment yet because of time constraint on my side. If this would be helpful I can try to dedicate some time to it.

### Versions

```
❯ nvim --version
NVIM v0.9.0-dev-91-gd339b4aad
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-10 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cmake.config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az334-638

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info

❯ nvim --headless -c 'lua print(require("obsidian").VERSION)' -c q
1.6.1%
```

**Comment by gerryhernandez** [comment]
I tried to reproduce this using my setup and I'm not able to; link completion is working as expected for me.

Let's try something basic, first. Try using the latest `main` git branch and see if your issue is resolved. There's a chance that #54 is related to your issue and it has been fixed, but not released. I'm running the latest code, myself, and I'm unable to reproduce your issue. Granted, we likely have wildly different overall configuration/environment, but it's worth trying.

If you're still experiencing the issue, see if you can publish your dotfiles somewhere, or at least share your related config snippets.

**Comment by BeCracked** [comment]
I should have mentioned that I am on the latest commit as well. Also saw #54 but that seems to be a different problem.

If I have some time tomorrow l'll try to find out which other plugin might cause this issue.

**Comment by epwalsh** [comment]
Hey @BeCracked, from the stack trace you posted, it looks like one of the notes in your vault has bad frontmatter. Specifically it sounds like there's a note with `aliases` in its frontmatter that is a string instead of a list of strings. I just a cut a PR to make Obsidian.nvim more robust to unexpected frontmatter like this.

**Comment by epwalsh** [comment]
Please reopen if it's still an issue.

**Comment by BeCracked** [comment]
The issue no longer occurs for me. Thanks!
